name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SKIP_JDK_VERSION_CHECK: "true"

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      id: setup-java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Install Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept licenses and install packages
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.0"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew --no-daemon build
